// Code generated by protoc-gen-go.
// source: protocol.proto
// DO NOT EDIT!

package protoes

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type CreateAcc struct {
	AccName          *string `protobuf:"bytes,1,req,name=accName" json:"accName,omitempty"`
	RoleName         *string `protobuf:"bytes,2,req,name=roleName" json:"roleName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateAcc) Reset()         { *m = CreateAcc{} }
func (m *CreateAcc) String() string { return proto.CompactTextString(m) }
func (*CreateAcc) ProtoMessage()    {}

func (m *CreateAcc) GetAccName() string {
	if m != nil && m.AccName != nil {
		return *m.AccName
	}
	return ""
}

func (m *CreateAcc) GetRoleName() string {
	if m != nil && m.RoleName != nil {
		return *m.RoleName
	}
	return ""
}

type CreateAccRet struct {
	Ok               *uint32 `protobuf:"varint,1,req,name=ok" json:"ok,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CreateAccRet) Reset()         { *m = CreateAccRet{} }
func (m *CreateAccRet) String() string { return proto.CompactTextString(m) }
func (*CreateAccRet) ProtoMessage()    {}

func (m *CreateAccRet) GetOk() uint32 {
	if m != nil && m.Ok != nil {
		return *m.Ok
	}
	return 0
}

type AccLogin struct {
	AccName          *string `protobuf:"bytes,1,req,name=accName" json:"accName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccLogin) Reset()         { *m = AccLogin{} }
func (m *AccLogin) String() string { return proto.CompactTextString(m) }
func (*AccLogin) ProtoMessage()    {}

func (m *AccLogin) GetAccName() string {
	if m != nil && m.AccName != nil {
		return *m.AccName
	}
	return ""
}

type AccLoginRet struct {
	Ok               *uint32 `protobuf:"varint,1,req,name=ok" json:"ok,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccLoginRet) Reset()         { *m = AccLoginRet{} }
func (m *AccLoginRet) String() string { return proto.CompactTextString(m) }
func (*AccLoginRet) ProtoMessage()    {}

func (m *AccLoginRet) GetOk() uint32 {
	if m != nil && m.Ok != nil {
		return *m.Ok
	}
	return 0
}

type AccLoinInfo struct {
	AccId            *uint32 `protobuf:"varint,1,req,name=accId" json:"accId,omitempty"`
	Lv               *uint32 `protobuf:"varint,2,req,name=lv" json:"lv,omitempty"`
	AccName          *string `protobuf:"bytes,3,req,name=accName" json:"accName,omitempty"`
	RoleName         *string `protobuf:"bytes,4,req,name=roleName" json:"roleName,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccLoinInfo) Reset()         { *m = AccLoinInfo{} }
func (m *AccLoinInfo) String() string { return proto.CompactTextString(m) }
func (*AccLoinInfo) ProtoMessage()    {}

func (m *AccLoinInfo) GetAccId() uint32 {
	if m != nil && m.AccId != nil {
		return *m.AccId
	}
	return 0
}

func (m *AccLoinInfo) GetLv() uint32 {
	if m != nil && m.Lv != nil {
		return *m.Lv
	}
	return 0
}

func (m *AccLoinInfo) GetAccName() string {
	if m != nil && m.AccName != nil {
		return *m.AccName
	}
	return ""
}

func (m *AccLoinInfo) GetRoleName() string {
	if m != nil && m.RoleName != nil {
		return *m.RoleName
	}
	return ""
}

func init() {
}
